openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/api/tasks:
    get:
      summary: ''
      operationId: getApiApiTasks
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      title: 'Test Title'
                      description: 'Lorem Ipsum Dolor sit amet.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T13:43:07.000000Z'
                      updated_at: '2024-11-19T13:43:07.000000Z'
                    -
                      id: 2
                      title: 'Test Title'
                      description: 'Lorem Ipsum Dolor sit amet.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T13:43:29.000000Z'
                      updated_at: '2024-11-19T13:43:29.000000Z'
                    -
                      id: 3
                      title: 'Test Title'
                      description: 'Lorem Ipsum Dolor sit amet.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T13:43:51.000000Z'
                      updated_at: '2024-11-19T13:43:51.000000Z'
                    -
                      id: 4
                      title: Mr.
                      description: 'Vero aut natus deleniti est nisi quos. Eos expedita praesentium in iste. Earum omnis omnis magnam cupiditate ea.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:24:28.000000Z'
                      updated_at: '2024-11-19T14:24:28.000000Z'
                    -
                      id: 5
                      title: Dr.
                      description: 'Corrupti non neque natus neque ipsum. Earum rem veniam laborum tenetur. Et cum in dolorem animi sequi.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:25:46.000000Z'
                      updated_at: '2024-11-19T14:25:46.000000Z'
                    -
                      id: 6
                      title: Prof.
                      description: 'Voluptatum occaecati hic illo et qui quis. Dolores aspernatur laborum et aut aut. Saepe deleniti atque aut. Deleniti repudiandae iure esse pariatur eligendi ipsa ipsam blanditiis.'
                      completed: true
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:26:34.000000Z'
                      updated_at: '2024-11-19T14:26:34.000000Z'
                    -
                      id: 8
                      title: Mr.
                      description: 'Exercitationem nihil quisquam consectetur suscipit. Dolorem quae animi voluptas et et modi. Libero dolor dolor velit molestiae ad.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:32:15.000000Z'
                      updated_at: '2024-11-19T14:32:15.000000Z'
                    -
                      id: 9
                      title: Mrs.
                      description: 'Est enim aperiam sed et repellendus itaque officia. Est distinctio enim officia iusto natus aut quia. Odit quos ut corporis rem ea eaque.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:32:52.000000Z'
                      updated_at: '2024-11-19T14:32:52.000000Z'
                    -
                      id: 10
                      title: Miss
                      description: 'Animi quaerat distinctio dolores dignissimos quod rem harum. Nobis rerum sunt impedit et voluptas voluptas et repellendus. Quo omnis dolores vel fugit repellendus.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:33:04.000000Z'
                      updated_at: '2024-11-19T14:33:04.000000Z'
                    -
                      id: 11
                      title: Prof.
                      description: 'Qui eum odit doloribus sed alias sed totam non. Iste molestiae autem commodi. Repellat sint qui commodi sunt. Et veniam dignissimos dicta natus laudantium nulla alias.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:39:35.000000Z'
                      updated_at: '2024-11-19T14:39:35.000000Z'
                    -
                      id: 12
                      title: Mr.
                      description: 'Natus voluptate veniam quia sed ullam hic officia. Nostrum ut aspernatur officia quam. Ut eius ab fugiat porro aspernatur et reiciendis. Nobis necessitatibus magni hic deleniti.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:39:35.000000Z'
                      updated_at: '2024-11-19T14:39:35.000000Z'
                    -
                      id: 13
                      title: Dr.
                      description: 'Excepturi laboriosam ipsum voluptatum. Quis quia est et id. Dolorum quos dignissimos modi sed. Quae repellendus veniam voluptatibus enim aut exercitationem voluptate molestias.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:39:35.000000Z'
                      updated_at: '2024-11-19T14:39:35.000000Z'
                    -
                      id: 14
                      title: Prof.
                      description: 'Ducimus consequatur occaecati dolor accusamus. Est laborum ut sit quis recusandae. Vel perspiciatis et dolor tempora eius.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:39:35.000000Z'
                      updated_at: '2024-11-19T14:39:35.000000Z'
                    -
                      id: 15
                      title: Miss
                      description: 'Nostrum tempora corporis sapiente quo. Et sit eum suscipit voluptas blanditiis voluptas molestiae. Mollitia dolorem voluptas nesciunt sit quia incidunt.'
                      completed: false
                      created_by: 'Deanna Boyle'
                      created_at: '2024-11-19T14:39:35.000000Z'
                      updated_at: '2024-11-19T14:39:35.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'Test Title'
                        description: 'Lorem Ipsum Dolor sit amet.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T13:43:07.000000Z'
                        updated_at: '2024-11-19T13:43:07.000000Z'
                      -
                        id: 2
                        title: 'Test Title'
                        description: 'Lorem Ipsum Dolor sit amet.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T13:43:29.000000Z'
                        updated_at: '2024-11-19T13:43:29.000000Z'
                      -
                        id: 3
                        title: 'Test Title'
                        description: 'Lorem Ipsum Dolor sit amet.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T13:43:51.000000Z'
                        updated_at: '2024-11-19T13:43:51.000000Z'
                      -
                        id: 4
                        title: Mr.
                        description: 'Vero aut natus deleniti est nisi quos. Eos expedita praesentium in iste. Earum omnis omnis magnam cupiditate ea.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:24:28.000000Z'
                        updated_at: '2024-11-19T14:24:28.000000Z'
                      -
                        id: 5
                        title: Dr.
                        description: 'Corrupti non neque natus neque ipsum. Earum rem veniam laborum tenetur. Et cum in dolorem animi sequi.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:25:46.000000Z'
                        updated_at: '2024-11-19T14:25:46.000000Z'
                      -
                        id: 6
                        title: Prof.
                        description: 'Voluptatum occaecati hic illo et qui quis. Dolores aspernatur laborum et aut aut. Saepe deleniti atque aut. Deleniti repudiandae iure esse pariatur eligendi ipsa ipsam blanditiis.'
                        completed: true
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:26:34.000000Z'
                        updated_at: '2024-11-19T14:26:34.000000Z'
                      -
                        id: 8
                        title: Mr.
                        description: 'Exercitationem nihil quisquam consectetur suscipit. Dolorem quae animi voluptas et et modi. Libero dolor dolor velit molestiae ad.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:32:15.000000Z'
                        updated_at: '2024-11-19T14:32:15.000000Z'
                      -
                        id: 9
                        title: Mrs.
                        description: 'Est enim aperiam sed et repellendus itaque officia. Est distinctio enim officia iusto natus aut quia. Odit quos ut corporis rem ea eaque.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:32:52.000000Z'
                        updated_at: '2024-11-19T14:32:52.000000Z'
                      -
                        id: 10
                        title: Miss
                        description: 'Animi quaerat distinctio dolores dignissimos quod rem harum. Nobis rerum sunt impedit et voluptas voluptas et repellendus. Quo omnis dolores vel fugit repellendus.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:33:04.000000Z'
                        updated_at: '2024-11-19T14:33:04.000000Z'
                      -
                        id: 11
                        title: Prof.
                        description: 'Qui eum odit doloribus sed alias sed totam non. Iste molestiae autem commodi. Repellat sint qui commodi sunt. Et veniam dignissimos dicta natus laudantium nulla alias.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:39:35.000000Z'
                        updated_at: '2024-11-19T14:39:35.000000Z'
                      -
                        id: 12
                        title: Mr.
                        description: 'Natus voluptate veniam quia sed ullam hic officia. Nostrum ut aspernatur officia quam. Ut eius ab fugiat porro aspernatur et reiciendis. Nobis necessitatibus magni hic deleniti.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:39:35.000000Z'
                        updated_at: '2024-11-19T14:39:35.000000Z'
                      -
                        id: 13
                        title: Dr.
                        description: 'Excepturi laboriosam ipsum voluptatum. Quis quia est et id. Dolorum quos dignissimos modi sed. Quae repellendus veniam voluptatibus enim aut exercitationem voluptate molestias.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:39:35.000000Z'
                        updated_at: '2024-11-19T14:39:35.000000Z'
                      -
                        id: 14
                        title: Prof.
                        description: 'Ducimus consequatur occaecati dolor accusamus. Est laborum ut sit quis recusandae. Vel perspiciatis et dolor tempora eius.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:39:35.000000Z'
                        updated_at: '2024-11-19T14:39:35.000000Z'
                      -
                        id: 15
                        title: Miss
                        description: 'Nostrum tempora corporis sapiente quo. Et sit eum suscipit voluptas blanditiis voluptas molestiae. Mollitia dolorem voluptas nesciunt sit quia incidunt.'
                        completed: false
                        created_by: 'Deanna Boyle'
                        created_at: '2024-11-19T14:39:35.000000Z'
                        updated_at: '2024-11-19T14:39:35.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'Test Title'
                        description:
                          type: string
                          example: 'Lorem Ipsum Dolor sit amet.'
                        completed:
                          type: boolean
                          example: true
                        created_by:
                          type: string
                          example: 'Deanna Boyle'
                        created_at:
                          type: string
                          example: '2024-11-19T13:43:07.000000Z'
                        updated_at:
                          type: string
                          example: '2024-11-19T13:43:07.000000Z'
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiApiTasks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nvdfonlgutqwqwxugfrxruagn
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: tempora
                  nullable: false
                completed:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
              required:
                - title
                - description
      security: []
  '/api/api/tasks/{id}':
    get:
      summary: ''
      operationId: getApiApiTasksId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    title: 'Test Title'
                    description: 'Lorem Ipsum Dolor sit amet.'
                    completed: true
                    created_at: '2024-11-19T13:43:07.000000Z'
                    updated_at: '2024-11-19T13:43:07.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Test Title'
                      description:
                        type: string
                        example: 'Lorem Ipsum Dolor sit amet.'
                      completed:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-11-19T13:43:07.000000Z'
                      updated_at:
                        type: string
                        example: '2024-11-19T13:43:07.000000Z'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'This field is required when none of <code>description</code> and <code>completed</code> are present. Must not be greater than 255 characters.'
                  example: rkwuelejnifg
                  nullable: false
                description:
                  type: string
                  description: 'This field is required when none of <code>title</code> and <code>completed</code> are present.'
                  example: null
                  nullable: false
                completed:
                  type: string
                  description: 'This field is required when none of <code>title</code> and <code>description</code> are present.'
                  example: null
                  nullable: false
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/api/tasks/{task_id}':
    delete:
      summary: ''
      operationId: deleteApiApiTasksTask_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: task_id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
